### ISSUE TITLE
ZCU102 Board

### ISSUE THREAD

**Issue by tanmayd26** [Lien182/ReconROS#13]
Hello, I was wondering how can I use ReconROS for ZCU102.

Thank you.

**Comment by Lien182** [comment]
Hello, not yet, but the extension would not be a big deal. Just create a template in the /templates folder (e.g., just copy a ZCU104 template, rename it, and adapt the export.tcl file accordingly).

**Comment by tanmayd26** [comment]
Also I am using noetic and not dashing. So should I still follow same steps for noetic?

**Comment by Lien182** [comment]
Unfortunately, ReconROS supports ROS 2 only. The ROS bridge may be an option, but I do not know how much the performance would suffer.

**Comment by ctgulzh** [comment]
Hello, I   was wondering how can I use ReconROS for Kria26. Are the improvement steps consistent with the ZCU102 improvement steps?  
Thank you!

**Comment by ctgulzh** [comment]
As for whether the kria26 development board needs to be remade ISO, the ZCU104 image provided on GitHub cannot be loaded when burned to the SD card.

**Comment by ctgulzh** [comment]
As for whether the kria26 development board needs to be remade ISO, the ZCU104 image provided on GitHub cannot be loaded when burned to the SD card.
Thank you!
